import express,{type NextFunction,type Request,type RequestHandler,type Response} from 'express';
import cookieParser from 'cookie-parser';
import multer from 'multer';
import {existsSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {authRouter} from './auth-routes.js';
import {optionalAuth,requireAuth,requireCampus,type AuthedRequest} from './auth.js';
import {all,dateIso,initDatabase,mapItem,one,pool,publicUser,run} from './db.js';
import {categories,cleanText,conditions,consumeRateLimit,isAllowedOrigin,statuses,validPrice} from './security.js';
import {CURRENCY_LIST} from './currency.js';
import {cosConfigured,decodeObjectKey,signedObjectUrl,uploadToCos,validImageSignature} from './storage.js';
import {canonicalPair,itemCardSnapshot,shouldSendItemCard} from './conversations.js';
import {mailConfigured,sendAdminCommentNotification,sendAdminFeedbackNotification,sendNewMessageNotification} from './mail.js';
import {publicSellerProfile} from './profiles.js';

const app=express(),port=Number(process.env.PORT)||8787,appOrigin=process.env.APP_ORIGIN||'http://localhost:5173';
const asyncRoute=(handler:(req:AuthedRequest,res:Response,next:NextFunction)=>Promise<unknown>):RequestHandler=>(req,res,next)=>{void handler(req,res,next).catch(next)};

app.disable('x-powered-by');app.set('trust proxy','loopback');app.use(express.json({limit:'1mb'}));app.use(cookieParser());
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');if(['POST','PUT','PATCH','DELETE'].includes(req.method)&&!isAllowedOrigin(req.headers.origin,appOrigin))return res.status(403).json({error:'请求来源不受信任'});next()});
app.use(optionalAuth);app.use('/api/auth',authRouter);

const itemSelect=`SELECT i.*,u.id AS seller_id,u.nickname AS seller_nickname,u.avatar_url AS seller_avatar,u.email AS seller_email,u.email_verified AS seller_email_verified FROM items i JOIN users u ON u.id=i.user_id`;

app.get('/api/items',asyncRoute(async(req,res)=>{
  const keyword=cleanText(req.query.keyword,40),category=cleanText(req.query.category,20),condition=cleanText(req.query.condition,20),schoolId=cleanText(req.query.schoolId,40)||'ruc_suzhou',sort=String(req.query.sort||'latest');
  const clauses=[`i.school_id=?`,`i.status='在售'`],args:any[]=[schoolId];
  if(keyword){clauses.push('(i.title LIKE ? OR i.description LIKE ?)');args.push(`%${keyword}%`,`%${keyword}%`)}
  if(category&&categories.includes(category as typeof categories[number])){clauses.push('i.category=?');args.push(category)}
  if(condition&&conditions.includes(condition as typeof conditions[number])){clauses.push('i.item_condition=?');args.push(condition)}
  const order=sort==='priceAsc'?'i.price ASC':sort==='priceDesc'?'i.price DESC':'i.created_at DESC';
  const rows=await all(`${itemSelect} WHERE ${clauses.join(' AND ')} ORDER BY ${order} LIMIT 100`,args);res.json({items:rows.map(mapItem),total:rows.length});
}));

app.get('/api/items/:id',asyncRoute(async(req,res)=>{
  const id=Number(req.params.id),row=await one(`${itemSelect} WHERE i.id=?`,[id]);if(!row)return res.status(404).json({error:'商品不存在或已删除'});
  const comments=await all(`SELECT c.*,u.nickname,u.avatar_url,u.verified,u.id AS author_id FROM comments c JOIN users u ON u.id=c.user_id WHERE c.item_id=? ORDER BY c.created_at DESC LIMIT 50`,[id]);
  const favorited=req.user?Boolean(await one('SELECT 1 FROM favorites WHERE user_id=? AND item_id=?',[req.user.id,id])):false;
  res.json({item:mapItem(row),favorited,comments:comments.map(c=>({id:Number(c.id),content:c.content,createdAt:c.created_at,author:{id:Number(c.author_id),nickname:c.nickname,avatarUrl:c.avatar_url,verified:Boolean(c.verified),isSeller:Number(c.author_id)===Number(row.user_id)}}))});
}));

app.get('/api/users/:id',asyncRoute(async(req,res)=>{const id=Number(req.params.id);if(!Number.isSafeInteger(id)||id<1)return res.status(404).json({error:'用户不存在'});const user=await one('SELECT id,email,nickname,avatar_url,email_verified FROM users WHERE id=?',[id]);if(!user)return res.status(404).json({error:'用户不存在'});const rows=await all(`${itemSelect} WHERE i.user_id=? AND i.status='在售' ORDER BY i.created_at DESC LIMIT 50`,[id]);res.json({profile:publicSellerProfile(user),items:rows.map(mapItem)})}));

function itemPayload(body:Record<string,unknown>){
  const title=cleanText(body.title,80),price=validPrice(body.price),category=cleanText(body.category,20),condition=cleanText(body.condition,20),description=cleanText(body.description,1000),images=Array.isArray(body.images)?body.images.map(v=>cleanText(v,800)).filter(Boolean).slice(0,9):[];
  if(title.length<3)throw new Error('商品标题至少需要 3 个字符');if(price===null)throw new Error('请输入有效价格');if(!categories.includes(category as typeof categories[number]))throw new Error('请选择有效分类');if(!conditions.includes(condition as typeof conditions[number]))throw new Error('请选择有效成色');return{title,price,category,condition,description,images};
}

app.post('/api/items',requireAuth,requireCampus,asyncRoute(async(req,res)=>{try{const d=itemPayload(req.body);const result=await run(`INSERT INTO items (user_id,title,price,images,category,item_condition,description,school_id) VALUES (?,?,?,?,?,?,?,?)`,[req.user!.id,d.title,d.price,JSON.stringify(d.images),d.category,d.condition,d.description,req.user!.schoolId]);res.status(201).json({id:result.insertId})}catch(e){res.status(400).json({error:e instanceof Error?e.message:'商品信息无效'})}}));

app.patch('/api/items/:id',requireAuth,requireCampus,asyncRoute(async(req,res)=>{const id=Number(req.params.id),existing=await one('SELECT * FROM items WHERE id=?',[id]);if(!existing)return res.status(404).json({error:'商品不存在'});if(Number(existing.user_id)!==req.user!.id)return res.status(403).json({error:'只能编辑自己发布的商品'});try{const d=itemPayload(req.body),status=cleanText(req.body.status,20)||String(existing.status);if(!statuses.includes(status as typeof statuses[number]))return res.status(400).json({error:'商品状态无效'});await run(`UPDATE items SET title=?,price=?,images=?,category=?,item_condition=?,description=?,status=? WHERE id=?`,[d.title,d.price,JSON.stringify(d.images),d.category,d.condition,d.description,status,id]);res.json({ok:true})}catch(e){res.status(400).json({error:e instanceof Error?e.message:'商品信息无效'})}}));

app.post('/api/items/:id/favorite',requireAuth,requireCampus,asyncRoute(async(req,res)=>{const id=Number(req.params.id);if(!await one('SELECT id FROM items WHERE id=?',[id]))return res.status(404).json({error:'商品不存在'});const existing=await one('SELECT 1 FROM favorites WHERE user_id=? AND item_id=?',[req.user!.id,id]);if(existing)await run('DELETE FROM favorites WHERE user_id=? AND item_id=?',[req.user!.id,id]);else await run('INSERT INTO favorites (user_id,item_id) VALUES (?,?)',[req.user!.id,id]);res.json({favorited:!existing})}));

app.post('/api/items/:id/comments',requireAuth,requireCampus,asyncRoute(async(req,res)=>{const id=Number(req.params.id),content=cleanText(req.body.content,200);if(content.length<2)return res.status(400).json({error:'评论至少需要 2 个字符'});const item=await one('SELECT id,title FROM items WHERE id=?',[id]);if(!item)return res.status(404).json({error:'商品不存在'});const result=await run('INSERT INTO comments (item_id,user_id,content) VALUES (?,?,?)',[id,req.user!.id,content]);void sendAdminCommentNotification(req.user!.nickname,String(item.title),content,id).catch(error=>console.error('Comment admin email failed:',error));res.status(201).json({id:result.insertId})}));

app.post('/api/feedback',requireAuth,asyncRoute(async(req,res)=>{if(!consumeRateLimit(`feedback:${req.user!.id}`,5,60*60_000))return res.status(429).json({error:'反馈提交过于频繁，请一小时后再试'});const type=cleanText(req.body.type,20),content=cleanText(req.body.content,1000),allowed=['问题反馈','功能建议','其他'];if(!allowed.includes(type))return res.status(400).json({error:'请选择反馈类型'});if(content.length<10)return res.status(400).json({error:'请至少填写 10 个字符，方便我们理解问题'});const result=await run('INSERT INTO feedback (user_id,feedback_type,content) VALUES (?,?,?)',[req.user!.id,type,content]);void sendAdminFeedbackNotification(req.user!.nickname,req.user!.email,type,content).catch(error=>console.error('Feedback admin email failed:',error));res.status(201).json({id:result.insertId})}));

app.get('/api/me/items',requireAuth,asyncRoute(async(req,res)=>{const rows=await all(`${itemSelect} WHERE i.user_id=? ORDER BY i.created_at DESC`,[req.user!.id]);res.json({items:rows.map(mapItem)})}));
app.get('/api/me/favorites',requireAuth,asyncRoute(async(req,res)=>{const rows=await all(`${itemSelect} JOIN favorites f ON f.item_id=i.id WHERE f.user_id=? ORDER BY f.created_at DESC`,[req.user!.id]);res.json({items:rows.map(mapItem)})}));
app.get('/api/me/stats',requireAuth,asyncRoute(async(req,res)=>{const s=await one(`SELECT COUNT(*) total,SUM(status='在售') selling,SUM(status='已售出') sold FROM items WHERE user_id=?`,[req.user!.id]);res.json({stats:{total:Number(s?.total||0),selling:Number(s?.selling||0),sold:Number(s?.sold||0)}})}));
app.get('/api/me/wallet',requireAuth,asyncRoute(async(req,res)=>{const balances=await all('SELECT currency,balance FROM wallets WHERE user_id=?',[req.user!.id]);const wallet:Record<string,{code:string;name:string;description:string;balance:number}>=Object.fromEntries(CURRENCY_LIST.map(c=>[c.code,{code:c.code,name:c.name,description:c.description,balance:0}]));for(const row of balances){const code=String(row.currency);if(wallet[code])wallet[code].balance=Number(row.balance)}const entries=await all('SELECT id,currency,amount,balance_after,reason,operator,created_at FROM currency_ledger WHERE user_id=? ORDER BY id DESC LIMIT 50',[req.user!.id]);res.json({wallet,entries:entries.map(e=>({id:Number(e.id),currency:String(e.currency),amount:Number(e.amount),balanceAfter:Number(e.balance_after),reason:String(e.reason),operator:String(e.operator),createdAt:dateIso(e.created_at)}))})}));
app.put('/api/me/profile',requireAuth,asyncRoute(async(req,res)=>{const nickname=cleanText(req.body.nickname,24),wechatId=cleanText(req.body.wechatId,40),emailNotifications=req.body.emailMessageNotifications!==false;if(nickname.length<2)return res.status(400).json({error:'昵称至少需要 2 个字符'});await run('UPDATE users SET nickname=?,wechat_id=?,email_message_notifications=? WHERE id=?',[nickname,wechatId,emailNotifications?1:0,req.user!.id]);res.json({user:publicUser(await one('SELECT * FROM users WHERE id=?',[req.user!.id]))})}));

app.post('/api/conversations',requireAuth,requireCampus,asyncRoute(async(req,res)=>{
  const itemId=Number(req.body.itemId),item=await one('SELECT * FROM items WHERE id=?',[itemId]);if(!item)return res.status(404).json({error:'商品不存在'});if(Number(item.user_id)===req.user!.id)return res.status(400).json({error:'不能和自己发起会话'});
  const [buyerId,sellerId]=canonicalPair(req.user!.id,Number(item.user_id)),connection=await pool.getConnection();
  try{await connection.beginTransaction();await connection.execute('INSERT INTO conversations (item_id,buyer_id,seller_id) VALUES (?,?,?) ON DUPLICATE KEY UPDATE id=id',[itemId,buyerId,sellerId]);const [conversationRows]=await connection.execute<any[]>('SELECT * FROM conversations WHERE buyer_id=? AND seller_id=? FOR UPDATE',[buyerId,sellerId]),conversation=conversationRows[0];const [detailRows]=await connection.execute<any[]>(`SELECT item_id FROM messages WHERE conversation_id=? AND message_type='item_card' ORDER BY id DESC LIMIT 1`,[conversation.id]),[recentRows]=await connection.execute<any[]>(`SELECT 1 FROM messages WHERE conversation_id=? AND message_type='item_card' AND item_id=? AND created_at>=DATE_SUB(CURRENT_TIMESTAMP,INTERVAL 1 HOUR) LIMIT 1`,[conversation.id,itemId]);if(shouldSendItemCard(detailRows[0]?.item_id,itemId,Boolean(recentRows.length))){const snapshot=itemCardSnapshot(item);await connection.execute(`INSERT INTO messages (conversation_id,sender_id,content,message_type,item_id,item_snapshot) VALUES (?,?,?,?,?,?)`,[conversation.id,req.user!.id,item.title,'item_card',itemId,JSON.stringify(snapshot)]);await connection.execute('UPDATE conversations SET item_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[itemId,conversation.id]);}await connection.commit();res.json({id:Number(conversation.id)});}catch(error){await connection.rollback();throw error}finally{connection.release()}
}));
app.get('/api/conversations/unread-count',requireAuth,asyncRoute(async(req,res)=>{const u=req.user!.id,row=await one(`SELECT COUNT(*) count FROM messages m JOIN conversations c ON c.id=m.conversation_id LEFT JOIN conversation_reads r ON r.conversation_id=c.id AND r.user_id=? WHERE (c.buyer_id=? OR c.seller_id=?) AND m.sender_id<>? AND m.id>COALESCE(r.last_read_message_id,0)`,[u,u,u,u]);res.json({count:Number(row?.count||0)})}));
app.get('/api/conversations',requireAuth,asyncRoute(async(req,res)=>{const u=req.user!.id,rows=await all(`SELECT c.*,i.title item_title,IF(c.buyer_id=?,s.nickname,b.nickname) partner_name,IF(c.buyer_id=?,s.avatar_url,b.avatar_url) partner_avatar,(SELECT IF(m.message_type='item_card',CONCAT('[商品] ',m.content),m.content) FROM messages m WHERE m.conversation_id=c.id ORDER BY m.id DESC LIMIT 1) last_message,(SELECT COUNT(*) FROM messages um LEFT JOIN conversation_reads ur ON ur.conversation_id=c.id AND ur.user_id=? WHERE um.conversation_id=c.id AND um.sender_id<>? AND um.id>COALESCE(ur.last_read_message_id,0)) unread_count FROM conversations c LEFT JOIN items i ON i.id=c.item_id JOIN users b ON b.id=c.buyer_id JOIN users s ON s.id=c.seller_id WHERE c.buyer_id=? OR c.seller_id=? ORDER BY c.updated_at DESC`,[u,u,u,u,u,u]);res.json({conversations:rows.map(r=>({id:Number(r.id),itemId:Number(r.item_id),itemTitle:r.item_title||'商品交流',partner:{nickname:r.partner_name,avatarUrl:r.partner_avatar},lastMessage:r.last_message||'',unreadCount:Number(r.unread_count||0),updatedAt:r.updated_at}))})}));
async function conversationForUser(id:number,userId:number){return one(`SELECT c.*,i.title item_title FROM conversations c LEFT JOIN items i ON i.id=c.item_id WHERE c.id=? AND (c.buyer_id=? OR c.seller_id=?)`,[id,userId,userId])}
app.get('/api/conversations/:id/messages',requireAuth,asyncRoute(async(req,res)=>{const id=Number(req.params.id),c=await conversationForUser(id,req.user!.id);if(!c)return res.status(404).json({error:'会话不存在'});const rows=await all(`SELECT m.*,u.nickname,u.avatar_url FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.conversation_id=? ORDER BY m.id ASC LIMIT 300`,[id]);res.json({conversation:{id,itemId:Number(c.item_id),itemTitle:c.item_title||'商品交流'},messages:rows.map(r=>({id:Number(r.id),content:r.content,type:r.message_type||'text',item:r.item_snapshot?(typeof r.item_snapshot==='string'?JSON.parse(r.item_snapshot):r.item_snapshot):null,createdAt:r.created_at,mine:Number(r.sender_id)===req.user!.id,sender:{nickname:r.nickname,avatarUrl:r.avatar_url}}))})}));
app.post('/api/conversations/:id/read',requireAuth,asyncRoute(async(req,res)=>{const id=Number(req.params.id);if(!await conversationForUser(id,req.user!.id))return res.status(404).json({error:'会话不存在'});const latest=await one('SELECT COALESCE(MAX(id),0) id FROM messages WHERE conversation_id=?',[id]);await run(`INSERT INTO conversation_reads (conversation_id,user_id,last_read_message_id) VALUES (?,?,?) ON DUPLICATE KEY UPDATE last_read_message_id=GREATEST(last_read_message_id,VALUES(last_read_message_id)),updated_at=CURRENT_TIMESTAMP`,[id,req.user!.id,Number(latest?.id||0)]);res.json({ok:true})}));
app.post('/api/conversations/:id/messages',requireAuth,requireCampus,asyncRoute(async(req,res)=>{const id=Number(req.params.id),conversation=await conversationForUser(id,req.user!.id);if(!conversation)return res.status(404).json({error:'会话不存在'});const content=cleanText(req.body.content,500);if(!content)return res.status(400).json({error:'消息不能为空'});const result=await run('INSERT INTO messages (conversation_id,sender_id,content) VALUES (?,?,?)',[id,req.user!.id,content]);await run('UPDATE conversations SET updated_at=CURRENT_TIMESTAMP WHERE id=?',[id]);const recipientId=Number(conversation.buyer_id)===req.user!.id?Number(conversation.seller_id):Number(conversation.buyer_id),recipient=await one(`SELECT email,email_message_notifications,(last_seen_at IS NULL OR last_seen_at<DATE_SUB(CURRENT_TIMESTAMP,INTERVAL 10 MINUTE)) should_email FROM users WHERE id=?`,[recipientId]);let emailNotification:'sent'|'recent_online'|'disabled'|'failed'='disabled';if(recipient?.email_message_notifications){if(!recipient.should_email)emailNotification='recent_online';else if(mailConfigured()){try{await sendNewMessageNotification(String(recipient.email),req.user!.nickname,content,id);emailNotification='sent'}catch(error){emailNotification='failed';console.error('New message email failed:',error)}}else emailNotification='failed'}res.status(201).json({id:result.insertId,emailNotification})}));

const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:9},fileFilter:(_r,f,cb)=>cb(null,['image/jpeg','image/png','image/webp','image/gif'].includes(f.mimetype))});
app.post('/api/uploads',requireAuth,requireCampus,upload.array('images',9),asyncRoute(async(req,res)=>{if(!cosConfigured())return res.status(503).json({error:'腾讯云对象存储尚未配置'});const files=(req.files||[]) as Express.Multer.File[];if(!files.length||files.some(f=>!validImageSignature(f.buffer)))return res.status(400).json({error:'请选择有效的 JPG、PNG、WebP 或 GIF 图片'});const urls=await Promise.all(files.map(file=>uploadToCos(file)));res.status(201).json({urls})}));
const avatarUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:2*1024*1024,files:1},fileFilter:(_r,f,cb)=>cb(null,['image/jpeg','image/png','image/webp'].includes(f.mimetype))});
app.post('/api/me/avatar',requireAuth,avatarUpload.single('avatar'),asyncRoute(async(req,res)=>{if(!cosConfigured())return res.status(503).json({error:'腾讯云对象存储尚未配置'});const file=req.file;if(!file||!validImageSignature(file.buffer))return res.status(400).json({error:'请选择有效的 JPG、PNG 或 WebP 图片'});const avatarUrl=await uploadToCos(file,'avatars');await run('UPDATE users SET avatar_url=? WHERE id=?',[avatarUrl,req.user!.id]);res.status(201).json({avatarUrl,user:publicUser(await one('SELECT * FROM users WHERE id=?',[req.user!.id]))})}));
app.get('/api/media/:token',asyncRoute(async(req,res)=>{const key=decodeObjectKey(String(req.params.token));if(!key)return res.status(404).end();res.setHeader('Cache-Control','private, max-age=600');res.redirect(await signedObjectUrl(key))}));

app.get('/api/health',asyncRoute(async(_req,res)=>{await pool.query('SELECT 1');res.json({ok:true,database:'mysql',storage:cosConfigured()?'cos':'not-configured'})}));
const dist=resolve(process.cwd(),'dist');if(existsSync(dist)){app.use(express.static(dist));app.use((req:Request,res:Response,next)=>{if(req.method!=='GET'||req.path.startsWith('/api/'))return next();res.sendFile(join(dist,'index.html'),error=>{if(error)next(error)})})}
app.use((error:unknown,req:Request,res:Response,_next:NextFunction)=>{console.error(error);const message=error instanceof multer.MulterError?(error.code==='LIMIT_FILE_SIZE'?(req.path==='/api/me/avatar'?'头像图片不能超过 2MB':'单张图片不能超过 5MB'):'图片上传失败'):'服务器暂时无法处理请求';res.status(500).json({error:message})});

initDatabase().then(()=>app.listen(port,()=>console.log(`Campus Market listening on http://localhost:${port}`))).catch(error=>{console.error('MySQL initialization failed:',error);process.exitCode=1});
